version: "3"
services:
    cliapp:
      image: cliapp
      build:
        context: ./dockerfiles
        dockerfile: Dockerfile.cliapp
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    webapp:
      image: webapp
      build:
        context: ./dockerfiles
        dockerfile: Dockerfile.webapp
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    redis:
        image: redis:latest

