version: "3"
services:
    cliapp:
      image: cliapp
      build:
        context: ./dockerfiles
        dockerfile: Dockerfile.cliapp
      volumes:
        - type: volume
          source: sharedVolume
          target: /opt/chimera/data
    webapp:
      image: webapp
      build:
        context: ./dockerfiles
        dockerfile: Dockerfile.cliapp
      ports:
        - "5000:80"
      volumes:
      - type: volume
        source: sharedVolume
        target: /opt/chimera/data

volumes:
    sharedVolume: